# Creating a Numpy Array

In [1]:
#Importing Numpy 
import numpy as np

## Different way to create Numpy array 

In [2]:
#1Converting other Python structure to arrays(List, tuples)
a = np.array([1,2,3])
print(a) #vector

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
#2d and 3d
b = np.array([[1,2,3],[4,5,6]])
print(b) #matrix

[[1 2 3]
 [4 5 6]]


In [5]:
#3d
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c) #tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [7]:
#Arrays of Ones
np.ones((3,4))  #to intialize the values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#Arrays of Zeros
np.zeros((3,4)) # to initalize values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#array of random number
np.random.random((2,2)) #to initalize with random numbers

array([[0.04482577, 0.64219208],
       [0.59971878, 0.58017563]])

In [10]:
#filling the same number to throughout the array 
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [11]:
#Arranging number with a spevific interval 
np.arange(10,30,5) #used to create on the go arrays 

array([10, 15, 20, 25])

In [12]:
#with reshape
np.arange(1,13).reshape(3,4) #Total numbers should be equal to the product of two numbers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
#Return evenly spaced numbers over a specified interval. # linear space/linearly space
np.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [15]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Inspection

In [16]:
#Shape of a array
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [17]:
#Changing the Shape of Array 
b = np.array([[1,2,3],[4,5,6]])
b.shape = (3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
#ndim
a1.ndim

1

In [20]:
#Total number of items 
print(a1.size)

10


In [21]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing DataType

In [22]:
#astype
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operation/Mathematics

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
#Scalar operations

#arthmetic - All arthemtic operations will work 
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
# relational operator
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
# vector Operations
# arthmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# Array Mathematical Functions

In [32]:
a1 =  np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[81., 70., 67.],
       [91., 23., 20.],
       [82., 65.,  1.]])

In [38]:
# max/min/sum/Prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

91.0
1.0
500.0
84758701482000.0


In [40]:
#min of each row
#0 =  Columns
#1= Row
print(np.max(a1,axis =1))

[81. 91. 82.]


In [43]:
#mean / median / std/ var
print(np.mean(a1, axis =1))
print(np.median(a1, axis =1))
print(np.std(a1, axis =1))
print(np.var(a1, axis =1))

[72.66666667 44.66666667 49.33333333]
[70. 23. 65.]
[ 6.01849003 32.78549815 34.87437773]
[  36.22222222 1074.88888889 1216.22222222]


In [45]:
#trigonometric functions -  Not gonna use it in Data science Ever
np.sin(a1)

array([[-0.62988799,  0.77389068, -0.85551998],
       [ 0.10598751, -0.8462204 ,  0.91294525],
       [ 0.31322878,  0.82682868,  0.84147098]])

In [50]:
#dot Product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(4,3)

np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [52]:
#log and exponents 
print(np.log(a1))
print(np.exp(a1))

[[4.39444915 4.24849524 4.20469262]
 [4.51085951 3.13549422 2.99573227]
 [4.40671925 4.17438727 0.        ]]
[[1.50609731e+35 2.51543867e+30 1.25236317e+29]
 [3.31740010e+39 9.74480345e+09 4.85165195e+08]
 [4.09399696e+35 1.69488924e+28 2.71828183e+00]]


In [56]:
#round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[95. 88. 19.]
 [88. 36. 81.]]
[[34. 15. 74.]
 [ 4.  0. 88.]]
[[71. 98. 53.]
 [81. 70. 13.]]


# Indexing & Slicing 

In [62]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1[0]

0

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a2[1,0]

4

In [70]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [74]:
a3[1,1,0]

6

In [75]:
# Slicing 
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
print(a1[2:5])
print(a1[2:5:2])

[2 3 4]
[2 4]


In [83]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2[0,:]

array([0, 1, 2, 3])

In [88]:
print(a2[:,2]) #Fething 3 Columns 

[ 2  6 10]


In [89]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [90]:
print(a2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [98]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [101]:
a2[1,::3]

array([4, 7])

In [107]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [109]:
a3 = np.arange(27).reshape(3,3,3)

In [114]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3[0,1,:]

array([3, 4, 5])

In [120]:
a3[1,:,1]

array([10, 13, 16])

In [122]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [127]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [132]:
a1
for i  in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [133]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [134]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [135]:
#Printing each item of ndarray
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshape

In [137]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [140]:
#ravel
a3.ravel() #converts to 1-d Array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [143]:
#horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [144]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [145]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [152]:
#Horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [153]:
#vertical Split
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [156]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]